[[redirects]]
  from = "/*"
  to = "week1/lab1.1.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "week1/lab1.2.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "week1/lab1.3.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "week2/lab2.1.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "week2/lab2.2.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "week2/lab2.3.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "week2/lab2.4.html"
  status = 200